# Generated by Django 6.0.2 on 2026-02-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('central', 'Central Division'), ('northern', 'Northern Division'), ('southern', 'Southern Division')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
