# Generated by Django 6.0.2 on 2026-02-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_division_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cell',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('Central Division', 'Central Division'), ('Northern Division', 'Northern Division'), ('Southern Division', 'Southern Division')], max_length=50, null=True),
        ),
    ]
