# Generated by Django 6.0.2 on 2026-02-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_wastereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='location_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
