# Generated by Django 6.0.2 on 2026-02-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WasteReport',
        ),
    ]
